(function () {
  'use strict';
  var E=window.Solitaire, state, original, history=[], selected=null, prefs={sound:false,theme:'farm',motion:true}, audio=null, busy=false, lastFocus=null, read=0;
  var symbols={hearts:'♥',clubs:'♣',diamonds:'♦',spades:'♠'}, ranks={1:'Ace',11:'Jack',12:'Queen',13:'King'}, crops={hearts:['🍎','Apples'],clubs:['🥔','Potatoes'],diamonds:['🥕','Carrots'],spades:['🌽','Corn']};
  function $(id){return document.getElementById(id);}
  function escapeHTML(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function label(c){return (ranks[c.rank]||c.rank)+' of '+c.suit;}
  function say(s){$('message').textContent=s;}
  function storage(key,value){try{if(arguments.length===1)return JSON.parse(localStorage.getItem(key));localStorage.setItem(key,JSON.stringify(value));return true;}catch(e){return null;}}
  function save(){var ok=storage('grampy-solitaire-v1',{state:state,original:original,history:history.slice(-80)});$('save-status').textContent=ok?'Your game is saved. No rush.':'Keep this page open to keep your game.';}
  function remember(){history.push(E.clone(state));if(history.length>80)history.shift();}
  function sound(kind){if(!prefs.sound)return;try{var AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audio=audio||new AC();if(audio.state==='suspended')audio.resume();var notes=kind==='win'?[523,659,784,1047]:kind==='foundation'?[523,659]:kind==='draw'?[260]:[390];notes.forEach(function(freq,i){var o=audio.createOscillator(),g=audio.createGain(),at=audio.currentTime+i*.12;o.type='sine';o.frequency.setValueAtTime(freq,at);g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(.065,at+.015);g.gain.exponentialRampToValueAtTime(.001,at+.18);o.connect(g);g.connect(audio.destination);o.start(at);o.stop(at+.2);});}catch(e){/* Sound is optional. */}}
  function attrs(src){return ' data-type="'+src.type+'" data-pile="'+src.pile+'" data-index="'+src.index+'"';}
  function cardHTML(c,src,offset){var rank=c.rank===1?'A':c.rank===11?'J':c.rank===12?'Q':c.rank===13?'K':c.rank;
    var style=offset!==undefined?' style="top:'+offset+'px"':'';
    if(!c.up)return '<div class="card back"'+style+' aria-hidden="true"><div class="back-design"><b>80</b><small>MILLER FARM</small></div></div>';
    var art=c.rank===13?['🚜','Tractor']:c.rank===12?['🐄','The herd']:c.rank===11?['🐦‍⬛','The crows']:crops[c.suit];
    var center=c.rank===1?'<span class="pip">'+symbols[c.suit]+'</span>':'<span>'+art[0]+'</span><small>'+art[1]+'</small>';
    return '<button class="card '+(E.red(c)?'red':'black')+'"'+attrs(src)+style+' aria-label="'+label(c)+'" draggable="true"><span class="corner">'+rank+'<span class="suit">'+symbols[c.suit]+'</span></span><span class="card-art" aria-hidden="true">'+center+'</span><span class="corner bottom" aria-hidden="true">'+rank+'<span class="suit">'+symbols[c.suit]+'</span></span></button>';
  }
  function render(){
    var active=document.activeElement, focus=active&&active.getAttribute('data-type')?{type:active.getAttribute('data-type'),pile:active.getAttribute('data-pile'),index:active.getAttribute('data-index')}:null;
    var html='<div class="pile"><button id="stock" class="'+(state.stock.length?'card back':'slot')+'" aria-label="'+(state.stock.length?'Draw a card, '+state.stock.length+' left':state.waste.length?'Turn over the deck and draw again':'Deck is empty')+'"'+(!state.stock.length&&!state.waste.length?' disabled':'')+'>'+(state.stock.length?'<span class="back-design"><b>80</b><small>MILLER FARM</small></span>':'↻<small>Again</small>')+'</button></div>';
    html+='<div class="pile">'+(state.waste.length?cardHTML(state.waste[state.waste.length-1],{type:'waste',pile:0,index:state.waste.length-1}):'<div class="slot" aria-hidden="true">·</div>')+'</div><div></div>';
    state.foundations.forEach(function(p,i){html+='<div class="pile">'+(p.length?cardHTML(p[p.length-1],{type:'foundation',pile:i,index:p.length-1}):'<button class="slot" data-type="foundation" data-pile="'+i+'" data-index="-1" aria-label="'+E.suits[i]+' foundation, start with an Ace">'+symbols[E.suits[i]]+'<small>Ace</small></button>')+'</div>';});
    $('top-piles').innerHTML=html;
    var width=($('game').clientWidth-(window.innerWidth<=600?14:48)-6*(window.innerWidth<=600?5:14))/7, height=Math.max(52,width*1.4), faceStep=window.innerWidth<=600?29:34, backStep=window.innerWidth<=600?12:17;
    html='';state.tableau.forEach(function(p,i){var off=0;html+='<div class="column" data-column="'+i+'"><button class="slot" data-type="tableau" data-pile="'+i+'" data-index="-1" aria-label="Empty column '+(i+1)+', Kings only"'+(p.length?' tabindex="-1" aria-hidden="true"':'')+'>K</button>';
      p.forEach(function(c,j){html+=cardHTML(c,{type:'tableau',pile:i,index:j},off);if(j<p.length-1)off+=c.up?faceStep:backStep;});
      html+='</div>';});$('tableau').innerHTML=html;
    var cols=$('tableau').children;state.tableau.forEach(function(p,i){var off=0;p.forEach(function(c,j){if(j<p.length-1)off+=c.up?faceStep:backStep;});cols[i].style.height=(off+height)+'px';});
    $('harvest').textContent='Harvest: '+E.count(state)+' / 52';$('moves').textContent='Moves: '+state.moves;$('undo').disabled=!history.length||busy;$('finish').hidden=!E.canFinish(state)||busy;
    if(selected){var el=findCard(selected);if(el)el.classList.add('selected');}
    if(focus){var next=findCard(focus);if(next)next.focus({preventScroll:true});}
  }
  function findCard(src){return document.querySelector('[data-type="'+src.type+'"][data-pile="'+src.pile+'"][data-index="'+src.index+'"]');}
  function srcFrom(el){return {type:el.getAttribute('data-type'),pile:+el.getAttribute('data-pile'),index:+el.getAttribute('data-index')};}
  function slide(from,el){if(!from||!el||!el.animate||!prefs.motion||(window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches))return;var to=el.getBoundingClientRect();el.style.zIndex='35';var animation=el.animate([{transform:'translate('+(from.left-to.left)+'px,'+(from.top-to.top)+'px)'},{transform:'translate(0,0)'}],{duration:220,easing:'ease-out'});animation.onfinish=function(){el.style.zIndex='';};}
  function perform(src,dst){if(!E.canMove(state,src,dst))return false;var c=E.pile(state,src)[src.index],el=findCard(src),from=el&&el.getBoundingClientRect(),newIndex=E.pile(state,dst).length;remember();E.move(state,src,dst);selected=null;render();slide(from,findCard({type:dst.type,pile:dst.pile,index:newIndex}));save();sound(dst.type==='foundation'?'foundation':'move');say(label(c)+(dst.type==='foundation'?' added to the harvest. Nicely done!':' moved. Keep growing those rows.'));if(state.won)win();return true;}
  function tap(src){if(busy||state.won)return;
    if(selected&&perform(selected,src))return;
    var p=E.pile(state,src),c=p&&p[src.index];if(!c){say(src.type==='foundation'?'Start each harvest pile with an Ace.':'An empty row needs a King.');return;}
    if(src.type==='foundation'){selected=src;render();say(label(c)+' selected. Tap a row to bring it back into play.');return;}
    var dest=E.destinations(state,src);
    if(dest.length){perform(src,dest[0]);return;}
    selected=src;render();say(label(c)+' has no spot yet. Try another card, or draw from the deck.');
  }
  function newGame(restart){busy=false;state=restart?E.clone(original):E.create();original=E.clone(state);history=[];selected=null;render();save();say('A fresh hand, just for you. Tap a card to get going.');}
  function hint(){if(busy||state.won)return;selected=null;render();var suggestions=E.hints(state);if(suggestions.length){var h=suggestions[0],c=E.pile(state,h.src)[h.src.index],el=findCard(h.src);if(el)el.classList.add('hinted');say('Try the '+label(c)+'. Tap the glowing card to move it.');if(el)el.scrollIntoView({block:'nearest',behavior:'auto'});}else if(state.stock.length||state.waste.length){$('stock').classList.add('hinted');say(state.stock.length?'Tap the deck at the top left to draw a card.':'Tap the empty deck to turn it over and look again.');}else{say('No more moves showing. You can Undo, or try a new game.');}}
  function undo(){if(!history.length||busy)return;state=history.pop();selected=null;render();save();sound('move');say('Last move undone. Take all the tries you need.');}
  function openModal(title,body){lastFocus=document.activeElement;$('modal-title').textContent=title;$('modal-body').innerHTML=body;$('modal-layer').hidden=false;$('close-modal').focus();}
  function closeModal(){$('modal-layer').hidden=true;if(lastFocus&&document.contains(lastFocus))lastFocus.focus();}
  function help(){openModal('A little helping hand','<h2>Make yourself at home.</h2><ol><li><b>Tap a face-up card.</b> It moves to an available spot for you. You can also drag cards with a mouse.</li><li><b>Build the rows down.</b> Put a red 6 on a black 7, for example. Only Kings can start an empty row.</li><li><b>Build the top piles up.</b> Collect each suit from Ace to King. Get all 52 cards up there to win.</li><li><b>Need another card?</b> Tap the deck at the top left. You can go through it as often as you like.</li></ol><p><b>Hint</b> lights up a move. <b>Undo</b> takes a move back. There’s no timer and no penalty.</p><div class="modal-actions"><button class="primary" data-close>Let’s play</button></div>');}
  function settings(){openModal('Make yourself comfortable','<h2>Your table, your way.</h2><label class="setting">Card backs<select id="card-theme"><option value="farm">Miller Farm</option><option value="falls">Cigar Falls</option><option value="harvest">Hay harvest</option></select></label><label class="setting">Gentle sound effects<input id="sound-check" type="checkbox"'+(prefs.sound?' checked':'')+'></label><label class="setting">Celebration animations<input id="motion-check" type="checkbox"'+(prefs.motion?' checked':'')+'></label><p>One card at a time. Easy undo. Always at your own pace.</p><div class="modal-actions"><button class="primary" data-close>Back to my game</button></div>');$('card-theme').value=prefs.theme;}
  function applyPrefs(){document.body.className='theme-'+prefs.theme+(prefs.motion?'':' reduce-motion');$('sound').innerHTML='<span aria-hidden="true">♫</span> Sound '+(prefs.sound?'on':'off');$('sound').setAttribute('aria-pressed',String(prefs.sound));storage('grampy-prefs-v1',prefs);}
  function switchView(mail){$('game-view').hidden=mail;$('mail-view').hidden=!mail;$('game-tab').classList.toggle('active',!mail);$('mail-tab').classList.toggle('active',mail);$('game-tab').setAttribute('aria-pressed',String(!mail));$('mail-tab').setAttribute('aria-pressed',String(mail));if(mail)showPost(read);else render();}
  function showPost(index){read=index;var posts=window.BIRTHDAY_POSTS;$('mail-list').innerHTML=posts.map(function(p,i){return '<button class="mail-item '+(i===index?'active':'')+'" data-post="'+i+'" aria-pressed="'+(i===index)+'"><span aria-hidden="true">'+p.icon+'</span><div><b>'+escapeHTML(p.subject)+'</b><small>'+escapeHTML(p.preview)+'</small></div></button>';}).join('');var p=posts[index];$('letter').innerHTML='<div class="letter-meta"><b>Subject:</b> '+escapeHTML(p.subject)+'<br><b>From:</b> '+escapeHTML(p.from)+'<br><b>To:</b> Grampy<br><b>Occasion:</b> Your 80th birthday</div>'+p.body;}
  function win(){sound('win');if(prefs.motion&&!(window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches)){var bits=['♥','♣','♦','♠','🌽','🥕','🍎','🥔'];for(var i=0;i<36;i++){var span=document.createElement('span');span.className='confetti';span.textContent=bits[i%bits.length];span.style.left=Math.random()*96+'%';span.style.animationDelay=Math.random()*1.5+'s';span.style.color=i%2?'#ffe195':'#fffef3';$('celebration').appendChild(span);}setTimeout(function(){$('celebration').innerHTML='';},5500);}openModal('A full harvest!','<div class="win-message"><div class="win-icon">🚜</div><h2>That’s a fine harvest, Grampy!</h2><p>All 52 cards, brought home.<br>Happy 80th birthday — here’s to many more good hands.</p><div class="modal-actions"><button class="primary" id="win-again">Play another hand</button><button data-close>Enjoy the moment</button></div></div>');}
  function finish(){if(!E.canFinish(state)||busy)return;busy=true;var tick=function(){if(!busy)return;var hints=E.hints(state).filter(function(h){return h.dst.type==='foundation';});if(!hints.length){busy=false;render();return;}perform(hints[0].src,hints[0].dst);if(state.won){busy=false;render();return;}setTimeout(tick,prefs.motion?130:0);};tick();}
  $('game').addEventListener('click',function(e){var el=e.target.closest('button');if(!el||busy)return;if(el.id==='stock'){if(state.won)return;remember();var recycling=!state.stock.length;E.draw(state);selected=null;render();save();sound('draw');say(recycling?'Deck turned over. Tap it again to draw a card.':label(state.waste[state.waste.length-1])+'. Tap it to play, or draw again.');return;}if(el.id==='finish'){finish();return;}if(el.hasAttribute('data-type'))tap(srcFrom(el));});
  var dragged=null;
  $('game').addEventListener('dragstart',function(e){var el=e.target.closest('[data-type]');if(!el||busy){e.preventDefault();return;}dragged=srcFrom(el);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain','card');});
  $('game').addEventListener('dragover',function(e){if(dragged){e.preventDefault();e.dataTransfer.dropEffect='move';}});
  $('game').addEventListener('drop',function(e){e.preventDefault();var el=e.target.closest('[data-type]'),col=e.target.closest('[data-column]'),dst=el?srcFrom(el):col?{type:'tableau',pile:+col.getAttribute('data-column')}:null;if(dragged&&dst&&!perform(dragged,dst))say('That card doesn’t fit there. Try Hint for a helping hand.');dragged=null;});
  $('game').addEventListener('dragend',function(){dragged=null;});
  $('new-game').onclick=function(){openModal('Deal another hand?','<h2>A fresh start?</h2><p>This will replace the hand on the table.</p><div class="modal-actions"><button id="confirm-new" class="primary">New shuffled game</button><button id="restart">Replay this hand</button><button data-close>Keep playing</button></div>');};
  $('undo').onclick=undo;$('hint').onclick=hint;$('help').onclick=help;$('settings').onclick=settings;
  $('sound').onclick=function(){prefs.sound=!prefs.sound;applyPrefs();sound('foundation');};
  $('game-tab').onclick=function(){switchView(false);};$('mail-tab').onclick=function(){switchView(true);};$('read-note').onclick=function(){switchView(true);$('mail-tab').focus();window.scrollTo(0,0);};$('home-button').onclick=function(){switchView(false);window.scrollTo(0,0);};
  $('close-modal').onclick=closeModal;
  $('modal-layer').addEventListener('click',function(e){var b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-close'))closeModal();if(b.id==='confirm-new'||b.id==='restart'||b.id==='win-again'){closeModal();newGame(b.id==='restart');}});
  $('modal-layer').addEventListener('change',function(e){if(e.target.id==='card-theme')prefs.theme=e.target.value;if(e.target.id==='sound-check'){prefs.sound=e.target.checked;sound('foundation');}if(e.target.id==='motion-check')prefs.motion=e.target.checked;applyPrefs();});
  $('mail-list').addEventListener('click',function(e){var b=e.target.closest('[data-post]');if(b){showPost(+b.getAttribute('data-post'));$('letter').focus();}});
  document.addEventListener('keydown',function(e){if(!$('modal-layer').hidden){if(e.key==='Escape')closeModal();if(e.key==='Tab'){var els=$('modal-layer').querySelectorAll('button,input,select,a[href]'),first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}if($('game-view').hidden)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo();}if(e.key==='Escape'){selected=null;render();}if(e.key.toLowerCase()==='h'&&!e.ctrlKey&&!e.metaKey)hint();});
  var resizeTimer;window.addEventListener('resize',function(){clearTimeout(resizeTimer);resizeTimer=setTimeout(function(){if(!$('game-view').hidden)render();},120);});
  var saved=storage('grampy-solitaire-v1'),storedPrefs=storage('grampy-prefs-v1');
  if(storedPrefs){prefs.sound=storedPrefs.sound===true;prefs.motion=storedPrefs.motion!==false;prefs.theme=['farm','falls','harvest'].indexOf(storedPrefs.theme)>=0?storedPrefs.theme:'farm';}applyPrefs();
  if(saved&&E.valid(saved.state)&&E.valid(saved.original)){state=saved.state;original=saved.original;history=Array.isArray(saved.history)?saved.history.filter(E.valid).slice(-80):[];render();save();say(state.won?'A full harvest! Start a new game whenever you’re ready.':'Welcome back, Grampy. Your cards are right where you left them.');}else{state=E.create();original=E.clone(state);render();save();}
}());

