(function(){'use strict';
var R=Royale,$=function(id){return document.getElementById(id);},KEY='solitaire-royale-v1',state,initial,history=[],selected=null,menu=null,drawMode=false,deal=false,scale=1,drag=null,secret='',memoryTimer=null,modalReturn=null;
var prefs={sound:true,fast:false,drag:true,left:false,large:false,back:0,face:0},tour=null,tournament=null,scores=[],savedNotice=false,storageOK=true;
var suitNames=['hearts','clubs','diamonds','spades'],rankNames=['','ace','2','3','4','5','6','7','8','9','10','jack','queen','king'];
function title(g){return R.titles[R.games.indexOf(g)];}
function say(t,announceOnly){$('status').textContent=announceOnly?'':t;$('announcer').textContent=t;}
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'null');}catch(e){return null;}}
function save(){try{localStorage.setItem(KEY,JSON.stringify({state:state,initial:initial,history:history,prefs:prefs,tour:tour,tournament:tournament,scores:scores}));}catch(e){storageOK=false;if(!savedNotice){savedNotice=true;say('Saving is unavailable. Use disk > save to a file.');}}}
var data=read();if(data&&R.valid(data.state)){state=data.state;initial=R.valid(data.initial)?data.initial:R.clone(state);history=(data.history||[]).filter(R.valid).slice(-40);Object.keys(prefs).forEach(function(k){if(data.prefs&&typeof data.prefs[k]===typeof prefs[k])prefs[k]=data.prefs[k];});tour=data.tour&&Array.isArray(data.tour.scores)&&data.tour.index>=0&&data.tour.index<8?data.tour:null;tournament=data.tournament&&Number.isFinite(data.tournament.seed)?data.tournament:null;scores=Array.isArray(data.scores)?data.scores.slice(0,5):[];if(state.flipped.length===2)R.conceal(state);}else{state=R.create('klondike');initial=R.clone(state);}
// Safari's visible area changes independently of the layout viewport during rotation.
var fitFrame=0,rotationTimers=[];
function fit(){
 fitFrame=0;
 var viewport=$('viewport'),visual=window.visualViewport;
 // Keep intentional pinch zoom usable; only fit the visible area at normal zoom.
 var visible=visual&&Math.abs(visual.scale-1)<.05;
 viewport.style.width=(visible?visual.width:window.innerWidth)+'px';
 viewport.style.height=(visible?visual.height:window.innerHeight)+'px';
 viewport.style.left=(visible?visual.offsetLeft:0)+'px';
 viewport.style.top=(visible?visual.offsetTop:0)+'px';
 var rect=viewport.getBoundingClientRect(),padding=getComputedStyle(viewport);
 var width=rect.width-(parseFloat(padding.paddingLeft)||0)-(parseFloat(padding.paddingRight)||0);
 var height=rect.height-(parseFloat(padding.paddingTop)||0)-(parseFloat(padding.paddingBottom)||0);
 if(width<=0||height<=0)return;
 scale=Math.min(width/640,height/400);
 $('screen').style.transform='scale('+scale+')';
}
function scheduleFit(){if(!fitFrame)fitFrame=requestAnimationFrame(fit);}
function settleFit(){
 scheduleFit();rotationTimers.forEach(clearTimeout);
 rotationTimers=[100,300,700,1200].map(function(delay){return setTimeout(scheduleFit,delay);});
}
window.addEventListener('resize',scheduleFit);
window.addEventListener('orientationchange',settleFit);
window.addEventListener('pageshow',settleFit);
if(window.screen.orientation&&window.screen.orientation.addEventListener)window.screen.orientation.addEventListener('change',settleFit);
if(window.visualViewport){window.visualViewport.addEventListener('resize',scheduleFit);window.visualViewport.addEventListener('scroll',scheduleFit);}
document.addEventListener('visibilitychange',function(){if(!document.hidden)settleFit();});
if(window.ResizeObserver)new ResizeObserver(scheduleFit).observe($('viewport'));
fit();
function audio(ok){if(!prefs.sound)return;try{var AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audio.ctx=audio.ctx||new AC();var ctx=audio.ctx;ctx.resume();var osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='square';osc.frequency.value=ok?660:165;gain.gain.setValueAtTime(.018,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.05);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.06);}catch(e){}}
function btn(text,action,cls){var b=document.createElement('button');b.type='button';b.textContent=text;if(cls)b.className=cls;b.addEventListener('click',action);return b;}
function point(p){return p.type+':'+(p.pile||0)+':'+(p.index===undefined?'':p.index);}
function closeMenu(){menu=null;$('menu-layer').replaceChildren();Array.prototype.forEach.call($('menubar').children,function(b){b.classList.remove('active');b.setAttribute('aria-expanded','false');});}
function closeDialog(){ $('dialog-layer').replaceChildren();closeMenu();if(modalReturn&&modalReturn.isConnected)modalReturn.focus();modalReturn=null;}
function dialog(heading,content,actions){if(menu==='how'){var menuBox=$('menu-layer').firstChild;if(menuBox){menuBox.style.maxHeight='50px';menuBox.style.overflow='hidden';menuBox.setAttribute('inert','');}}else closeMenu();selected=null;drawMode=false;modalReturn=document.activeElement;var shade=document.createElement('div');shade.className='modal-shade';shade.setAttribute('aria-hidden','true');var box=document.createElement('section');box.className='dialog';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.setAttribute('aria-label',heading);var h=document.createElement('h1');h.textContent=heading;var body=document.createElement('div');body.className='body';if(typeof content==='string')content.split('\n\n').forEach(function(t){var p=document.createElement('p');p.textContent=t;body.appendChild(p);});else body.appendChild(content);var bar=document.createElement('div');bar.className='actions';(actions||[{label:'ok',run:closeDialog},{label:'cancel',run:closeDialog}]).forEach(function(a){bar.appendChild(btn(a.label,a.run));});box.append(h,body,bar);$('dialog-layer').replaceChildren(shade,box);bar.firstChild.focus();return body;}
function confirm(text,run){dialog('start a new game',text,[{label:'ok',run:function(){closeDialog();run();}},{label:'cancel',run:closeDialog}]);}
function snapshot(){history.push(R.clone(state));if(history.length>40)history.shift();}
function change(fn,message){snapshot();if(!fn()){history.pop();audio(false);say(message||'That move is not available. Try another card.');return false;}selected=null;drawMode=false;audio(true);save();render();if(state.won)win();return true;}
function start(g,seed,keep){clearTimeout(memoryTimer);if(!keep){tour=null;tournament=null;}state=R.create(g,seed);initial=R.clone(state);history=[];selected=null;drawMode=false;deal=!prefs.fast;save();render();deal=false;closeMenu();say('Select a card, then its destination. How to play explains '+title(g)+'.',true);}
function newGame(g){confirm('Deal a new game of '+title(g)+'? Your current game will be replaced.',function(){if(g==='concentration'){var c=document.createElement('div');c.append(btn('one player',function(){closeDialog();start(g);},'choice'),btn('two players',function(){closeDialog();start(g);state.players=2;initial=R.clone(state);save();render();},'choice'));dialog('concentration',c);}else start(g);});}
function undo(){clearTimeout(memoryTimer);closeMenu();if(!history.length){say('There are no moves to undo.');return;}state=history.pop();selected=null;drawMode=false;if(state.flipped.length===2)R.conceal(state);save();render();say('Move undone.');}
function scoreText(){return state.game==='reno'&&!tour?'winnings: $'+R.score(state)*5+'   balance: $'+(R.score(state)*5-52):state.game==='concentration'&&state.players===2?'player '+(state.player+1)+'   scores: '+state.points.join(' / '):'score: '+R.score(state)+'   moves: '+state.moves;}
function cardLabel(c,p){return !c.up?(state.game==='concentration'?'Face-down card '+(p.pile+1):'Face-down card'):rankNames[c.r]+' of '+suitNames[c.s]+', '+(p.type==='tableau'?'column '+(p.pile+1):p.type);}
var positions=[];
function render(){
 $('table').replaceChildren();positions=[];
 var g=state.game,regular=['klondike','canfield','reno','calculation'].indexOf(g)>=0;
 function slot(p,x,y,w,h,label){h=Math.round(w*92/72);if(prefs.left)x=640-x-w;var el=btn(label,function(){activate(p);},'slot'+(p.type==='stock'?' stock':''));Object.assign(el.style,{left:x+'px',top:y+'px',width:w+'px',height:h+'px'});el.setAttribute('aria-label',label);el.dataset.point=point(p);$('table').appendChild(el);positions.push({p:p,x:x,y:y,w:w,h:h,el:el});return el;}
 function cards(p,x,y,w,h,step){h=Math.round(w*92/72);var a=R.pile(state,p);if(!a)return;var spread=step||0;for(var i=0;i<a.length;i++){if(!spread&&i<a.length-1)continue;var pos={type:p.type,pile:p.pile||0,index:i},c=a[i],xx=x,yy=y+i*spread,hh=h;if(p.type==='waste'&&state.game!=='pyramid'&&a.length>1){if(i<a.length-3)continue;xx+=Math.max(0,i-(a.length-3))*12;yy=y;}
 if(prefs.left)xx=640-xx-w;var el=btn('',function(q){return function(){activate(q);};}(pos),'card'+(selected&&point(selected)===point(pos)?' selected':'')+(deal?' dealing':''));Object.assign(el.style,{left:xx+'px',top:yy+'px',width:w+'px',height:hh+'px',zIndex:String(i+1)});el.setAttribute('aria-label',cardLabel(c,pos));el.setAttribute('aria-pressed',selected&&point(selected)===point(pos)?'true':'false');el.dataset.point=point(pos);var img=document.createElement('img');img.src=RoyaleCards.make(c,prefs.back,prefs.face);img.alt='';img.draggable=false;el.appendChild(img);$('table').appendChild(el);positions.push({p:pos,x:xx,y:yy,w:w,h:hh,el:el});
 if(prefs.drag&&c.up&&!['pyramid','pairs','wish','concentration'].includes(g))bindDrag(el,pos);}}
 function group(type,index,x,y,w,h,step,label){var p={type:type,pile:index};slot(p,x,y,w,h,label||type);cards(p,x,y,w,h,step);}
 if(regular){var n=state.tableau.length,w=72,h=92;group('stock',0,12,12,w,h,0,state.stock.length?'stock':'turn stock');group('waste',0,94,12,w,h,(g==='klondike'||g==='canfield')?1:0,'waste');for(var f=0;f<4;f++)group('foundations',f,280+f*88,12,w,h,0,g==='calculation'?'+'+(f+1):'foundation');if(state.reserve.length)group('reserve',0,12,132,w,h,0,'holding pile');for(var t=0;t<n;t++){var x=n===7?12+t*90:280+t*88;var count=state.tableau[t].length;var dy=Math.min(22,Math.max(6,(220-h)/Math.max(1,count-1)));group('tableau',t,x,130,w,h,dy,'empty column '+(t+1));}}
 if(g==='golf'){for(var t=0;t<7;t++)group('tableau',t,12+t*90,12,64,90,25,'column '+(t+1));group('stock',0,12,236,64,90,0,'stock');group('foundations',0,102,236,64,90,0,'foundation');}
 if(g==='pyramid'){for(var i=0;i<28;i++){var row=Math.floor((Math.sqrt(8*i+1)-1)/2),col=i-row*(row+1)/2;if(state.tableau[i].length)cards({type:'tableau',pile:i},294-row*36+col*72,8+row*32,52,74,0);}group('stock',0,12,252,52,74,0,'stock');group('waste',0,84,252,52,74,0,'waste');}
 if(g==='corners'){group('stock',0,12,12,56,80,0,'stock');group('waste',0,92,12,56,80,0,'waste');[[260,12],[460,12],[260,240],[460,240]].forEach(function(p,i){group('foundations',i,p[0],p[1],56,80,0,'foundation');});[[360,12],[260,126],[360,126],[460,126],[360,240]].forEach(function(p,i){group('tableau',i,p[0],p[1],56,80,0,'empty column');});}
 if(g==='shuffles'){state.tableau.forEach(function(p,i){group('tableau',i,10+(i%8)*78,10+Math.floor(i/8)*126,50,70,Math.min(14,48/Math.max(1,p.length-1)),'column '+(i+1));});for(var f=0;f<4;f++)group('foundations',f,326+f*78,274,50,70,0,'foundation');}
 if(g==='concentration'){for(var i=0;i<24;i++)if(state.tableau[i].length)cards({type:'tableau',pile:i},80+(i%6)*84,6+Math.floor(i/6)*86,52,74,0);}
 if(g==='wish'){for(var i=0;i<8;i++)group('tableau',i,142+(i%4)*104,8+Math.floor(i/4)*162,64,90,16,'column '+(i+1));}
 if(g==='pairs'){var pts=[];for(var i=0;i<6;i++)pts.push([64+i*86,8]);for(var i=0;i<4;i++)pts.push([64+i*172,102]);for(var i=0;i<6;i++)pts.push([64+i*86,236]);pts.forEach(function(p,i){if(state.tableau[i].length)cards({type:'tableau',pile:i},p[0],p[1],52,74,0);});group('reserve',0,294,132,52,74,0,'turn holding pile');}
 $('caption').replaceChildren();var cap=$('caption');cap.style.left='12px';cap.style.display=['pyramid','concentration','pairs','wish'].includes(g)?'none':'block';cap.style.bottom=(g==='golf'?48:34)+'px';var lg=document.createElement('div');lg.className='logo';var logo=document.createElement('img');logo.src='./assets/original-logo.png';logo.alt='solitaire royale';lg.appendChild(logo);var sm=document.createElement('small');sm.textContent=title(g)+'\n'+scoreText();sm.style.whiteSpace='pre-line';cap.append(lg,sm);if(g==='klondike'){cap.style.left='12px';cap.style.bottom='30px';cap.style.opacity=state.tableau.slice(0,3).some(function(p){return p.length>6;})?'0':'1';}else cap.style.opacity='1';if(g==='golf')cap.style.left='204px';
 say(title(g)+'   '+scoreText()+(tour?'   tour '+(tour.index+1)+'/8':'')+(drawMode?'   select a buried card to draw':''));
 }
function activate(p){
 if(drag&&drag.moved)return;if($('dialog-layer').children.length)return;closeMenu();
 var c=R.card(state,p),g=state.game;
 if(state.won){win();return;}
 if(g==='concentration'){if(state.flipped.length===2){clearTimeout(memoryTimer);R.conceal(state);}change(function(){return p.type==='tableau'&&R.flip(state,p.pile);});if(state.flipped.length===2)memoryTimer=setTimeout(function(){R.conceal(state);save();render();},1100);return;}
 if(g==='pairs'&&p.type==='reserve'&&c&&!c.up){change(function(){return R.draw(state);});return;}
 if(g==='golf'&&p.type==='tableau'){change(function(){return R.move(state,p,{type:'foundations',pile:0});});return;}
 if(selected&&point(selected)===point(p)){selected=null;drawMode=false;if(p.type==='stock')change(function(){return R.draw(state);});else render();return;}
 if(selected){var pairing=['pyramid','pairs','wish'].includes(g);var dst={type:p.type,pile:p.pile};if(pairing?R.pair(R.clone(state),selected,p):R.canMove(state,selected,dst,drawMode)){var src=selected,isDraw=drawMode;change(function(){return pairing?R.pair(state,src,p):R.move(state,src,dst,isDraw);});return;}}
 if(selected&&selected.type==='stock'&&p.type==='waste'){change(function(){return R.draw(state);});return;}
 if(g==='pyramid'&&c&&c.r===13&&R.exposed(state,p)){change(function(){return R.pair(state,p);});return;}
 if(p.type==='stock'){
   if(c&&c.up&&!selected){selected=p;render();say('Select a matching card or destination. Tap stock again to turn it.',true);return;}
   change(function(){return R.draw(state);},'No more stock cards are available.');return;
 }
 if(p.type==='reserve'&&g==='pairs'&&!c){return;}
 if(c&&c.up&&(drawMode||R.exposed(state,p)||p.type==='tableau'&&['klondike','canfield','reno'].includes(g))){selected=p;render();say(cardLabel(c,p)+' selected. Choose a destination.',true);}else{audio(false);say('Choose an exposed card or turn the stock.');}
}
// Pointer dragging supplements the original select-then-place interaction.
function bindDrag(el,p){el.addEventListener('pointerdown',function(e){if(e.button!==0)return;drag={p:p,x:e.clientX,y:e.clientY,el:el,moved:false};el.setPointerCapture(e.pointerId);});el.addEventListener('pointermove',function(e){if(!drag||drag.el!==el)return;var dx=(e.clientX-drag.x)/scale,dy=(e.clientY-drag.y)/scale;if(Math.abs(dx)+Math.abs(dy)>6){drag.moved=true;el.classList.add('dragging');el.style.transform='translate('+dx+'px,'+dy+'px)';}});el.addEventListener('pointerup',function(e){if(!drag)return;var d=drag;if(!d.moved){drag=null;return;}var rect=$('table').getBoundingClientRect(),x=(e.clientX-rect.left)/scale,y=(e.clientY-rect.top)/scale,dest=null;positions.forEach(function(pos){if(x>=pos.x&&x<=pos.x+pos.w&&y>=pos.y&&y<=pos.y+pos.h)dest=pos.p;});setTimeout(function(){drag=null;},0);if(dest&&R.canMove(state,d.p,{type:dest.type,pile:dest.pile})){change(function(){return R.move(state,d.p,{type:dest.type,pile:dest.pile});});}else{render();say('Choose a legal destination for that card.');}});el.addEventListener('pointercancel',function(){drag=null;render();});}
function hint(){closeMenu();var h=R.hint(state);if(!h){say(state.game==='concentration'?'Turn two cards and remember their positions.':state.stock.length?'Try turning the stock.':state.game==='shuffles'?'Use help to reshuffle or draw a buried card.':'No available move found. You can undo or start a new deal.');return;}render();[h.a,h.b].forEach(function(p){if(!p)return;positions.forEach(function(pos){if(pos.p.type===p.type&&pos.p.pile===p.pile&&(p.index===undefined||p.index===pos.p.index))pos.el.classList.add('hinted');});});say('The highlighted cards show a possible move.');}
var help={pyramid:'Remove pairs totaling 13; kings alone. Clear every card. A card covered only by its partner may pair.',golf:'Play adjacent ranks onto the foundation. No wrapping. Kings stop play until you draw. Clear the tableau.',canfield:'Build alternating colours downward; foundations upward from aces. Draw three. Fill spaces from the reserve first.',corners:'Build down regardless of suit; foundations up by suit from the starting rank. Wrap kings/aces. One stock pass.',calculation:'Foundations count by 1, 2, 3, 4. Wrap after kings. Tableau cards move only to foundations.',shuffles:'Build down by suit; foundations up. No filling spaces. Two reshuffles and one buried-card draw are available.',reno:'Canfield with single-card drawing and one stock pass. Each foundation card earns five virtual dollars.',concentration:'Find matching ranks. Fewest flips wins solo. Two players alternate after mismatches.',pairs:'Match the reserve with tableau cards. After the reserve empties, match tableau pairs. One exception if blocked.',wish:'Match exposed ranks to uncover cards. Clear all eight piles.'};
function how(g){var text=g==='klondike'?'The objective is to move all of the cards to the foundation.\n\nTwenty-eight cards are dealt into a tableau of 7 columns, with the first column on the left containing 1 card, the second column 2 cards, and continuing to the 7th column which contains 7 cards. When the game begins, all cards in the tableau are face down except for the fully exposed top card in each column which is face up.\n\nThe stock is turned 3 cards at a time onto a waste pile. Select the stock pile to turn the cards.\n\nBuild columns downward in alternating colours. Move an entire face-up sequence to another column. Empty columns take kings. Foundations start with aces and build upward by suit. Recycle the stock as often as you like.':help[g];dialog(title(g),text+'\n\nTap a card, then its destination. You can also drag. The help menu offers undo and hints. Your game saves after every move.');}
function tourScores(done){var wrap=document.createElement('div'),table=document.createElement('table'),total=0;R.games.slice(0,8).forEach(function(g,i){var tr=document.createElement('tr'),td=document.createElement('td'),v=document.createElement('td'),n=tour.scores[i];td.textContent=title(g);v.textContent=n===undefined?'--':n;total+=n||0;tr.append(td,v);table.appendChild(tr);});var p=document.createElement('p');p.textContent='total: '+total+' / 416';wrap.append(table,p);dialog(done?'tour complete':'tour score',wrap);}
function nextTour(){if(!tour)return;confirm('Record this score and continue to the next game?',function(){tour.scores[tour.index]=R.score(state);if(tour.index===7){var total=tour.scores.reduce(function(a,b){return a+b;},0);scores.push({score:total,date:new Date().toLocaleDateString()});scores.sort(function(a,b){return b.score-a.score;});scores=scores.slice(0,5);if(tournament){tournament.results.push({name:tournament.player,score:total});tournament.completed=true;}tourScores(true);tour=null;save();}else{tour.index++;start(R.games[tour.index],tour.seed+tour.index,true);tourScores(false);}});}
function beginTour(seed,keep){tour={index:0,scores:[],seed:seed===undefined?Math.floor(Math.random()*4294967296):seed};if(!keep)tournament=null;start('pyramid',tour.seed,true);}
function tournamentSetup(){var wrap=document.createElement('div'),p=document.createElement('p');p.textContent='Take turns on this iPad. Each player gets the same deals. Choose a game or the complete tour.';wrap.appendChild(p);R.games.slice(0,8).concat('tour').forEach(function(g){wrap.appendChild(btn(g==='tour'?'complete tour':title(g),function(){tournament={game:g,seed:Math.floor(Math.random()*4294967296),results:[],player:'',completed:false};playerSetup();},'choice'));});dialog('tournament play',wrap);}
function playerSetup(){var wrap=document.createElement('div'),input=document.createElement('input');input.maxLength=24;input.placeholder='player name';input.setAttribute('aria-label','Player name');wrap.appendChild(input);dialog('next tournament player',wrap,[{label:'play',run:function(){var name=input.value.trim()||'player '+(tournament.results.length+1);tournament.player=name;tournament.completed=false;closeDialog();if(tournament.game==='tour')beginTour(tournament.seed,true);else{tour=null;start(tournament.game,tournament.seed,true);}save();}},{label:'cancel',run:closeDialog}]);input.focus();}
function finishTournament(){if(!tournament||tournament.completed)return;if(tour){nextTour();return;}confirm('Record this player\'s score?',function(){tournament.results.push({name:tournament.player,score:R.score(state)});tournament.completed=true;save();showTournament();});}
function showTournament(){var w=document.createElement('div');tournament.results.slice().sort(function(a,b){return b.score-a.score;}).slice(0,5).forEach(function(s){var p=document.createElement('p');p.textContent=s.name+': '+s.score;w.appendChild(p);});if(!w.children.length)w.textContent='No scores recorded yet.';dialog('tournament high scores',w,[{label:'next player',run:playerSetup},{label:'ok',run:closeDialog}]);}
function win(){dialog('you win!',title(state.game)+' complete!\n\n'+scoreText()+'\n\nWell played.',[{label:tour?'next game':tournament?'record score':'new game',run:function(){closeDialog();if(tour)nextTour();else if(tournament)finishTournament();else newGame(state.game);}},{label:'ok',run:closeDialog}]);}
function installation(){dialog('add to your iPad Home Screen','Open this page in Safari.\n\n1. Tap Share (the square with an upward arrow).\n2. Choose Add to Home Screen.\n3. Keep Open as Web App enabled, if shown.\n4. Tap Add.\n\nLaunch the new Solitaire icon for a screen with just the game. Turn the iPad sideways for the largest cards.\n\n'+(navigator.serviceWorker&&navigator.serviceWorker.controller?'The game is ready for offline play.':'Stay online for the first visit so the game can be saved for offline play.'));}
function download(){save();var blob=new Blob([JSON.stringify({format:'solitaire-royale',state:state,initial:initial,history:history,tour:tour,tournament:tournament})],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='solitaire-royale-save.json';a.click();setTimeout(function(){URL.revokeObjectURL(url);},5000);closeMenu();say('Saved game file created.');}
$('open-file').addEventListener('change',function(e){var f=e.target.files[0];if(!f)return;if(f.size>1000000){dialog('open game','That file is too large.');return;}var reader=new FileReader();reader.onload=function(){try{var v=JSON.parse(reader.result);if(v.format!=='solitaire-royale'||!R.valid(v.state))throw Error();confirm('Replace the current game with this saved game?',function(){clearTimeout(memoryTimer);state=v.state;initial=R.valid(v.initial)?v.initial:R.clone(state);history=Array.isArray(v.history)?v.history.filter(R.valid).slice(-40):[];tour=v.tour&&Array.isArray(v.tour.scores)&&v.tour.index>=0&&v.tour.index<8?v.tour:null;tournament=v.tournament&&Array.isArray(v.tournament.results)&&Number.isFinite(v.tournament.seed)?v.tournament:null;if(state.flipped.length===2)R.conceal(state);save();render();});}catch(err){dialog('open game','That file is not a valid Solitaire Royale save. Your current game is unchanged.');}};reader.readAsText(f);e.target.value='';});
function popup(name,items,x){closeMenu();menu=name;var m=document.createElement('div');m.className='menu'+(prefs.large?' large':'');m.style.left=x+'px';m.setAttribute('role','menu');items.forEach(function(item){if(!item){m.appendChild(document.createElement('hr'));return;}var b=btn(item.label,item.run,item.checked?'checked':'');b.setAttribute('role','menuitem');if(item.disabled)b.disabled=true;m.appendChild(b);});$('menu-layer').appendChild(m);m.style.left=Math.max(0,Math.min(x,640-m.offsetWidth))+'px';var nav=$('menubar').querySelector('[data-menu="'+name+'"]');if(nav){nav.classList.add('active');nav.setAttribute('aria-expanded','true');}}
function gamesMenu(name,fn){var items=R.games.slice(0,8).map(function(g){return{label:title(g),run:function(){fn(g);}};});items.push(null,{label:"tour (aunt anne's game)",run:function(){if(name==='how')dialog('tour','Play all eight games in order. Each card scored contributes to a total out of 416. Use help > next tour game when ready.');else confirm('Begin a new eight-game tour?',function(){beginTour();});}},{label:'tournament play',run:function(){if(name==='how')dialog('tournament play','Players take turns with identical shuffled deals. Record a score under help, then select the next player.');else tournamentSetup();}},{label:"children's games >",run:function(){popup(name,R.games.slice(8).map(function(g){return{label:title(g),run:function(){fn(g);}};}),name==='how'?208:0);}});return items;}
function chooseDeck(kind){
 var wrap=document.createElement('div'),tabs=document.createElement('div');tabs.className='deck-tabs';
 ['backs','faces'].forEach(function(tab){var button=btn('card '+tab,function(){chooseDeck(tab);});button.setAttribute('aria-pressed',kind===tab?'true':'false');tabs.appendChild(button);});
 var grid=document.createElement('div');grid.className='deck-grid';
 var names=kind==='backs'?RoyaleCards.backs:RoyaleCards.faces;
 names.forEach(function(name,i){var current=kind==='backs'?prefs.back:prefs.face;var button=btn('',function(){if(kind==='backs')prefs.back=i;else prefs.face=i;save();render();chooseDeck(kind);},'deck-option');button.setAttribute('aria-label',name+' '+(kind==='backs'?'card back':'card faces'));button.setAttribute('aria-pressed',current===i?'true':'false');var img=document.createElement('img');img.alt='';img.src=kind==='backs'?RoyaleCards.make(null,i,prefs.face):RoyaleCards.make({s:0,r:13,up:true},prefs.back,i);var label=document.createElement('span');label.textContent=name;button.append(img,label);grid.appendChild(button);});
 wrap.append(tabs,grid);dialog('select a deck',wrap,[{label:'ok',run:closeDialog}]);
}
function showMenu(name){if(menu===name){closeMenu();return;}if(name==='new')popup(name,gamesMenu(name,newGame),0);if(name==='how')popup(name,gamesMenu(name,how),208);
 if(name==='help'){var items=[{label:'how to play this game',run:function(){how(state.game);}},{label:'start this game over',run:function(){confirm('Return to the original deal?',function(){clearTimeout(memoryTimer);state=R.clone(initial);history=[];save();render();});}},{label:'back up a move',run:undo,disabled:!history.length},{label:'show a possible move',run:hint}];if(state.game==='shuffles')items.push(null,{label:'reshuffle ('+(2-state.shuffles)+' left)',run:function(){closeMenu();change(function(){return R.reshuffle(state);});},disabled:state.shuffles>=2},{label:'draw a card once',run:function(){closeMenu();drawMode=true;selected=null;say('Select any buried card, then a legal destination.');},disabled:state.drawUsed});if(tour)items.push(null,{label:'next tour game',run:nextTour},{label:'show tour score',run:function(){tourScores(false);}});if(tournament)items.push(null,{label:'record tournament score',run:finishTournament,disabled:tournament.completed},{label:'next tournament player',run:playerSetup},{label:'tournament high scores',run:showTournament});popup(name,items,260);}
 if(name==='settings'){var items=['sound','fast','drag','left','large'].map(function(k,i){return{label:['sound effects','fast deal','drag cards','left handed','larger touch menus'][i],checked:prefs[k],run:function(){prefs[k]=!prefs[k];save();render();menu=null;showMenu('settings');}};});items.push(null,{label:'select a deck >',run:function(){chooseDeck('backs');}},{label:'add to Home Screen',run:installation});popup(name,items,400);}
 if(name==='disk')popup(name,[{label:'save game',run:function(){save();closeMenu();say(storageOK?'Game saved on this device.':'Saving unavailable. Use save to a file.');}},{label:'save to a file',run:download},{label:'open saved file',run:function(){closeMenu();$('open-file').click();}},null,{label:'tour high scores',run:function(){dialog('tour high scores',scores.length?scores.map(function(s,i){return(i+1)+'. '+s.score+'   '+s.date;}).join('\n'):'Complete a tour to set your first score.');}},{label:'about solitaire royale',run:function(){var w=document.createElement('div'),p=document.createElement('p');p.textContent='Solitaire Royale\nA native web recreation for the iPad.\n\nOriginal game: Software Resources International / Spectrum HoloByte, 1987.\n\nOriginal EGA card graphics and title decoded from the 1987 game data. All ten backs and five sets of face artwork are available. Menu font reconstructed from the DOS reference. Rules cross-checked with the original player\'s guide.\n\nBuilt for Grampy, with love from Ethan.\nNo accounts, ads, or tracking.';w.appendChild(p);var a=document.createElement('a');a.href='https://mirrors.apple2.org.za/ftp.apple.asimov.net/documentation/games/misc/Solitaire_Royale-Manual.pdf';a.target='_blank';a.rel='noopener';a.textContent='original player\'s guide';w.appendChild(a);var source=document.createElement('a');source.href='https://archive.org/details/msdos_Solitaire_Royale_1987';source.target='_blank';source.rel='noopener';source.textContent='original graphics source';w.append(document.createElement('br'),source);dialog('about',w);}}],416);
}
[['new','start a new game'],['how','how to play'],['help','help'],['settings','settings'],['disk','disk']].forEach(function(a){var b=btn(a[1],function(){showMenu(a[0]);});b.dataset.menu=a[0];b.setAttribute('aria-haspopup','menu');b.setAttribute('aria-expanded','false');$('menubar').appendChild(b);});
document.addEventListener('pointerdown',function(e){if(menu&&!e.target.closest('#menubar,.menu'))closeMenu();});
document.addEventListener('keydown',function(e){
 if(e.target.matches('input,textarea')){if(e.key==='Escape')closeDialog();return;}
 if(e.key==='Escape'){closeMenu();closeDialog();selected=null;drawMode=false;render();return;}
 if($('dialog-layer').children.length){if(e.key==='Tab'){var focusable=$('dialog-layer').querySelectorAll('button,input,a'),first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}
 if(menu&&['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();var bs=Array.from($('menu-layer').querySelectorAll('button:not(:disabled)')),ix=bs.indexOf(document.activeElement);ix=e.key==='Home'?0:e.key==='End'?bs.length-1:(ix+(e.key==='ArrowDown'?1:-1)+bs.length)%bs.length;bs[ix].focus();return;}
 if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo();return;}
 if(e.key==='F1'){e.preventDefault();how(state.game);return;}
 if(!e.ctrlKey&&!e.metaKey&&!e.altKey&&!e.repeat&&e.key.length===1){secret=(secret+e.key.toLowerCase()).slice(-5);if(secret==='lilly'){secret='';change(function(){var all=[];['stock','waste','reserve'].forEach(function(k){all=all.concat(state[k]);state[k]=[];});state.tableau.forEach(function(p){all=all.concat(p);p.length=0;});state.foundations.forEach(function(p){all=all.concat(p);p.length=0;});all=all.concat(state.removed);state.removed=[];if(['pyramid','pairs','wish','concentration'].includes(state.game))state.removed=all;else if(state.game==='golf')state.foundations[0]=all;else all.forEach(function(c){c.up=true;state.foundations[c.s].push(c);});state.foundations.forEach(function(p){p.sort(function(a,b){return a.r-b.r;});});state.flipped=[];clearTimeout(memoryTimer);state.won=true;state.moves++;return true;});}}
});
window.addEventListener('royale-cards-ready',render);render();save();
window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',function(){if(document.hidden)save();});
if('serviceWorker' in navigator){window.addEventListener('load',function(){navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(function(reg){reg.update();}).catch(function(){say('Online play is ready. Offline setup will retry next visit.');});});}
}());
